### ISSUE TITLE
PermissionError: [Errno 13] Permission denied in Userland Android HomeAssistant

### ISSUE THREAD

**Issue by peruggini** [ifaddr/ifaddr#64]
I got the error that is preventing me from successfully loading HomeAssistant, long story short I focused the issue with the example script in https://pypi.org/project/ifaddr/

```
(hass) userland@localhost:~$ python ./script.py 
Traceback (most recent call last):
  File "/home/userland/./script.py", line 3, in <module>
    adapters = ifaddr.get_adapters(include_unconfigured=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userland/hass/lib/python3.12/site-packages/ifaddr/_posix.py", line 56, in get_adapters
    raise OSError(eno, os.strerror(eno))
PermissionError: [Errno 13] Permission denied
```

Is there something I can investigate to get into this Permission Error?
Please note that running with su give the same result.

**Comment by jstasiak** [comment]
Hi, I'm not familiar with this environment (Userland Android) at all, I'm afraid I can't help with that.

**Comment by kohend** [comment]
If I will make a PR that fails over to using ifconfig CLI to get the info, will it be relevant?

**Comment by kohend** [comment]
To use home assistant on Android, I commented out the zeroconf function that uses ifaddr, it reduces some functionality, but it works. @peruggini
